[tool.poetry]
name = "python-text-to-audio"
version = "0.1.0"
description = "A desktop app that converts text and PDF files to audio using text-to-speech."
authors = ["Brandon Williams"]

[tool.poetry.dependencies]
python = "^3.8"
PyPDF2 = "^3.0.1"
pyttsx3 = "^2.90"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
